name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: make
      run: make
    - name: test run
      run: |
        sudo ./webserv &
        sleep 3
        ps -p $!



  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: make -C tests
      run: make -C tests
    - name: make check
      run: make check -C tests



  unit-tests-leaks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -x
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install valgrind
        elif [ "$RUNNER_OS" == "macOS" ]; then
            :
        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi
    - name: make -C tests
      run: make -C tests
    - name: Run leak test
      run: |
        set -x
        if [ "$RUNNER_OS" == "Linux" ]; then
            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=42 ./tests/build/tests
        elif [ "$RUNNER_OS" == "macOS" ]; then
            MallocStackLoggingNoCompact=1
            leaks ./tests/build/tests
        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi
