name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ${{ matrix.os }}
  strategy:
    fail-fast: false
    matrix:
      os: [ubuntu-latest, macos-latest]
  build:
    steps:
    - uses: actions/checkout@v2

    - name: make
      run: make
  unit-tests:
    steps:
    - uses: actions/checkout@v2

    - name: make -C tests
      run: make -C tests
    - name: make check
      run: make check -C tests
