name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: |
        set -x
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install valgrind
        elif [ "$RUNNER_OS" == "macOS" ]; then
            :
        fi
    - run: make
    - run: npm install
    - name: npm test
      run: |
        set -x
        # sudo ./webserv &
        PID=
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo valgrind --log-file=valgrind_output --leak-check=full --show-leak-kinds=definite,indirect,possible --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=42 ./webserv &
            PID=$!
            npm test
            sudo ps -a
            sudo kill -SIGTERM $PID
            ps
            ps -a
            sudo ps
            sudo ps -a
            echo '#####################################'
            # wait $PID || true
            # sudo wait $PID || true
            # sudo waitpid $PID || true
            # waitpid $PID || true
            echo '#####################################'
            cat valgrind_output
            echo $SHELL
        elif [ "$RUNNER_OS" == "macOS" ]; then
            MallocStackLoggingNoCompact=1
            ./webserv &
            PID=$!
            npm test
            leaks webserv
            sudo kill $PID
        fi
        # pkill -SIGINT webserv || true        # || true the time to fix signal... And maybe change and manage TERM signal ?

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - run: make -C tests
    - name: make check
      run: make check -C tests

  unit-tests-leaks:
    needs: unit-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -x
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install valgrind
        elif [ "$RUNNER_OS" == "macOS" ]; then
            :
        fi
    - name: make -C tests
      run: make -C tests
    - name: Run leak test
      run: |
        set -x
        cd tests
        if [ "$RUNNER_OS" == "Linux" ]; then
            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=42 ./build/tests
        elif [ "$RUNNER_OS" == "macOS" ]; then
            # MallocStackLoggingNoCompact=1
            # ./build/tests &
            # leaks ./build/tests
            :
        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi
