name: Generate UML diagrams

on:
  push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip3 install hpp2plantuml

    - name: Generate new ump
      run: |
        git checkout -b uml
        git push --set-upstream origin uml
        git config user.name github-actions
        git config user.email github-actions@github.com
        hpp2plantuml  -i "./includes/**/*.hpp" -o docs/diagrams/src/webserv.plantuml
        git add docs/diagrams/src/webserv.plantuml
        git commit -m "github action: updating UML diagram"
        git push
