name: Generate UML diagrams

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        set -x
        sudo apt-get install graphviz
        pip3 install hpp2plantuml
        wget https://sourceforge.net/projects/plantuml/files/1.2021.9/plantuml.1.2021.9.jar -O ../plantuml.jar

    - name: Generate new uml
      run: |
        set -x
        ls -l ..
        git checkout -b uml
        git config user.name github-actions
        git config user.email github-actions@github.com
        # hpp2plantuml -d -i "./includes/**/*.hpp" -o docs/diagrams/src/webserv.puml
        hpp2plantuml -i "./includes/**/*.hpp" -o docs/diagrams/src/webserv.puml
        
        java -jar ../plantuml.jar "docs/diagrams/src/webserv.puml" -o ../out
        java -jar ../plantuml.jar "docs/diagrams/src/webserv.puml" -o ../out -tsvg

        git fetch
        git merge origin/master
        git add docs/
        git commit -m "github action: updating UML diagram"
        git push -f -u origin uml
