name: Generate UML diagrams

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        set -x
        # apt install graphiz
        pip3 install hpp2plantuml
        wget https://sourceforge.net/projects/plantuml/files/1.2021.9/plantuml.1.2021.9.jar -O ../plantuml.jar

    - name: Generate new ump
      run: |
        set -x
        ls -l ..
        git checkout -b uml
        git config user.name github-actions
        git config user.email github-actions@github.com
        hpp2plantuml  -i "./includes/**/*.hpp" -o docs/diagrams/src/webserv.puml
        
        java -jar plantuml.jar "docs/diagrams/src/webserv.puml" -o ../out
        java -jar plantuml.jar "docs/diagrams/src/webserv.puml" -o ../out -tsvg

        git add docs/diagrams/src/webserv.plantuml
        git commit -m "github action: updating UML diagram"
        git push --set-upstream origin uml
        git push

